### ISSUE TITLE
Cadastre Redesign - Fair Launch Claim

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#101]
View For: Any user that starts a claim (single-click on an unpopulated coordinate on the map) during the fair launch period
Current Reference: https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimInfo.js & https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimAction.js

1. Display the Auction Details plus existing claim instructions, wireframe 7.1 in the left panel upon the first click of the map when in the fair launch period.
2. Auction Details (as defined inthe FairLaunchClaimer contract, live updated)
    * Current Required Bid = startingBid - priceDecrease
    * Auction End = auctionEnd
    * Time Remaining = auctionEnd - Current datetime
3. Upon a second click on the map (parcel shape locked), display the panel as shown in wireframe 7.2
    * Max Claim Payment (to Treasury) = Current Required Bid
    * Stream & Stream Buffer calculated/displayed as in other windows
4. The `Wrap to ETHx` opens the Wrap ETH modal shown in wireframe 11.1
5. The `Claim` button submits the entered data to the appropriate Ceramic stream fields+pinning and smart contract transactions (which require wallet signing)
6. Display the "Streaming Info Box" defined in https://github.com/Geo-Web-Project/cadastre/issues/94 below the transaction submission buttons.
7. Conform styling to existing Cadastre styling (wireframes below show functionality and spacing).

<img width="764" alt="7 1" src="https://user-images.githubusercontent.com/15019279/160211209-2da03529-bd7f-42c1-9027-785087b4609b.png">

<img width="765" alt="7 2" src="https://user-images.githubusercontent.com/15019279/160211224-f2512e53-1b1d-499a-817b-e7ddb46bbec0.png">

**Bounty Overview**
Size = M
Payment = 500 DAI (for the two issues)
To Be Completed With: https://github.com/Geo-Web-Project/cadastre/issues/95
Assignee = 

**Bounty Submission**
When work is complete, please create PR with your work and request review from both @codynhat & @gravenp. @gravenp will handle logistics of payment with you privately.

**Comment by codynhat** [comment]
@zhyd1997 The main difference here from the simple claim view is checking if the `FairLaunchClaimer` is currently in an auction. https://github.com/Geo-Web-Project/core-contracts/blob/main/contracts/FairLaunchClaimer.sol#L21-L24

**Comment by zhyd1997** [comment]
@codynhat 

The 2 variables here are `BigNumber` type, if I convert them to JS `Date` type, is it correct?

**Comment by codynhat** [comment]
Yea, they should be timestamps in seconds.

**Comment by gravenp** [comment]
Great work @zhyd1997! We'll pay out this bounty this weekend when we do the SourceCred runs.

**Comment by gravenp** [comment]
Bounty paid out here: https://etherscan.io/tx/0x4ff7ff2f9ddce00d21619fb01c2a0e6bf6c93ea96a9cd24c5e0d7dacbaa69104

Thanks again, @zhyd1997 !
