### ISSUE TITLE
Cadastre Redesign - Land Portfolio/Payments Dashboard

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#104]
View For: Any user
Current Reference: Wallet Pop-Up Modal

**Requirements**
1. The Land Portfolio/Payments Dashboard should be structured as shown in the attached wireframe
2. The dashboard should be accessible via a user clicking on the wallet element in the header or the link in https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/StreamingInfo.tsx
3. Display the (shortened) connected wallet address (0x + 4 digits + ... + final 4 digits)
4. Include a "Disconnect" button next to the wallet address
5. Display a warning above the wallet balances that informs the user when their ETHx balance will reach 0 at their current stream rate
    * ETHx Balance Exhaustion Datetime = Current Datetime + (Current ETHx Balance/Net Current Stream Rate)
    * If the balance is 0 or negative, show the warning: "Your ETHx balance is 0. Any Geo Web parcels you previously licensed have been put in foreclosure."
7. Display the connected wallet's ETH and ETHx balances in their respective sections.
8. Add a widget under the ETHx Balance that makes it easy for users to copy the proper ETHx smart contract address or add it to Metamask (https://github.com/Geo-Web-Project/cadastre/blob/main/components/CopyTokenAddress.tsx).
9. Allow the user to trigger wrap and unwrapping transactions in their respective sections
10. The Portfolio table should display all of the connected wallet's licenses and bids:
    * For valid licenses without outstanding bids
      * Status = Valid
      * Action Date = null
      * Price, Fee, & Buffer Deposit = License values
      * Action Button = View (teal)
    * For valid licenses with outstanding bids:
      * Status = Incoming Bid (red text)
      * Action Date = Bid Response Deadline (Bid Datetime + 7 Days) (red text)
      * Price, Fee, & Buffer Deposit = Bid values
      * Action Button = Respond (red)
    * For the user's open bids (license still owned by someone else): 
      * Status = Outgoing Bid
      * Action Date = Bid Response Deadline (Bid Datetime + 7 Days)
      * Price, Fee, & Buffer Deposit = Bid values
      * Action Button = View (teal)
    * For the user's licenses that have had their stream closed:
      * Status = In Foreclosure (red text)
      * Action Date = Datetime of stream closed (note that this will always be a datetime in the past) (red text)
      * Price = Current dutch auction price
      * Fee & Buffer Deposit = null
      * Action Button = Reclaim (red)
    * For licenses with a winning bid that hasn't been processed (user is the previous or to-be license):
      * Status = Needs Transfer (red text)
      * Action Date = Lesser of Bid Response Deadline or Acceptance Trigger (Bid Datetime + 7 Days or when the previous licensor stopped their stream) (red text)
      * Price, Fee, & Buffer Deposit = Bid values
      * Action Button = Trigger (red)
11. The Portfolio table should be scrollable when there are more entries than can be displayed in the modal
12. The table should be sortable by columns (default to Parcel ID, ascending)
13. Exit the modal and navigate to the respective parcel in the appropriate transition context, if the user clicks the respective `Action` Button
14. Display the "Total" row for the numeric columns below the table
15. Conform styling to existing Cadastre styling (wireframes below show functionality and spacing).

**Bounty Overview**
Size = M
Payment = 500 DAI
Assignee =

**Bounty Submission**
When work is complete, please create a PR based on and to the latest `develop` branch. Request review from both @codynhat & @gravenp. @gravenp will handle the logistics of payment with you privately.

**Comment by codynhat** [comment]
@gravenp When should this dashboard be shown? Does it replace the profile view? Or is there a separate button somewhere?

**Comment by gravenp** [comment]
Yeah, it replaces the profile view and then it's also linked from the info box created in this ticket https://github.com/Geo-Web-Project/cadastre/issues/94

**Comment by codynhat** [comment]
![image](https://user-images.githubusercontent.com/6885592/183733992-d7d1add1-5ce3-47d4-99a5-0ceb335f81c1.png)
