### ISSUE TITLE
Cadastre Redesign - Create a Wrap ETH Modal

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#105]
View For: Any user
Current Reference: N/A

1. Create a new modal which allows users to wrap their ETH into ETHx
2. Display the connected wallet's current ETH balance (in decimal form)
3. Display the conencted wallet's current ETHx balance (in decimal form)
4. Entry field should accept any positive floating point value in ETH (transaction will be deominated in wei)
5. 
<img width="746" alt="11 1" src="https://user-images.githubusercontent.com/15019279/160211476-ee505203-6801-4d74-90b1-b70697bf80f9.png">

Bounty Overview
Size = S
Payment = 250 DAI 
Assignee = https://github.com/zhyd1997

Bounty Submission
When work is complete, please create PR with your work and request review from both @codynhat & @gravenp. @gravenp will handle the logistics of payment with you privately.

**Comment by zhyd1997** [comment]
Hi, @codynhat @gravenp 

IMO, the wrapped **ETH** token is **wETH**, but why it's **ETHx** here?

**Comment by codynhat** [comment]
Yea, we are using ETHx here (not WETH), but still using the "wrapping" terminology.

ETHx is a Superfluid SuperToken. More helpful info can be found here:
- https://github.com/superfluid-finance/protocol-monorepo/tree/dev/packages/sdk-core#supertoken-functions
- https://docs.superfluid.finance/superfluid/

Their terminology is "upgrading" ETH into ETHx.

**Comment by zhyd1997** [comment]
@codynhat get it, thanks 👍

**Comment by gravenp** [comment]
@zhyd1997 this bounty was just paid here: https://etherscan.io/tx/0x678fa1c2b417bff1c8d22e3676a17c74b0b21063b66d946f04b6dc5a746c903b. Great job! Closing this issue.
