### ISSUE TITLE
Integrate Superfluid SDK-Redux

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#111]
Add [Redux](https://redux.js.org) and [SDK-Redux](https://github.com/superfluid-finance/protocol-monorepo/tree/dev/packages/sdk-redux) for easier state management of Superfluid flows.

This unblocks several issues that interact with Superfluid.

**Comment by gravenp** [comment]
We discussed this issue having a bounty before Cody started, but I never added it.  We'll call it a "Small" size issue for 250 DAI paid out in the next tranche of payments.

**Comment by gravenp** [comment]
250 DAI bounty paid along with Cody's outstanding SourceCred grain balance here: https://etherscan.io/tx/0xde9d4049e241b0954d4bd6249b31801826f5c756e1d4bd68de01d5c41fd4299c
