### ISSUE TITLE
Create and associate a new Ceramic Doc ID with parcel transfers

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#17]
When a land parcel transfer is made, a new Ceramic doc (owned by the new land licensor) needs to be created and associated to the land parcel to allow the transaction to go through and grant the new licensor control of the parcel name and linked web content.

**Comment by gravenp** [comment]
Land transfer transactions appear to be blocked by this issue.

**Comment by codynhat** [comment]
https://github.com/Geo-Web-Project/core-contracts/pull/13/commits/f9f7312136c30f5c19e6c91cb02a63652a2a6b14
