### ISSUE TITLE
Linked wallet under a 3ID shows "purchase" action

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#18]
There are some new patterns to learn here when using 3ID Connect. Basically a 3ID can have multiple blockchain wallets linked to it. However, the cadastre UI picks a single wallet to determine whether that wallet is the "owner" of a parcel. If it is the owner, it shows the editing view instead of the purchasing view.

Currently, when a wallet is selected that is not the owner of a parcel, but is linked to the 3ID that owns the Ceramic doc for that parcel, they can successfully edit the doc within the purchase view.

@gravenp Should we use the 3ID as the main form of identity on the cadastre? This means that the cadastre will show all parcels owned by all wallets under that 3ID as their own, instead of only parcels from a single wallet.

**Comment by gravenp** [comment]
Hmmmm. Would they always be signing into the Cadastre with the wallet ID though? "Jumping up a level" might cause some confusion and lead to unintended cross wallet editing or transactions (say they have business and personal wallet IDs). You could make the argument that they shouldn't link them under the same 3ID in the first place if they want to keep those things separate. But then are we (incorrectly or correctly) encouraging a user to use multiple 3IDs (which is likely our key for governance and DAO functions)?

**Comment by gravenp** [comment]
I think we should have a quick chat about what we'd want for DAO/governance IDs then work back from there.

**Comment by gravenp** [comment]
Alright trying to untangle a bit of the knot here:

1. We want unique individuals (not businesses, not wallets) to participate in governance and voting. 
2. There are valid reasons that users would want wallets to remain separate although they may be effectively controlled by the same individual.

Number 1 points to using 3ID for governance purposes. Number 2 just points to the Cadastre UX ensuring someone doesn't accidentally cross-wallet edit or fund transactions. I think that's more important than any minor convenience gain. So I'd lean toward keeping wallet ID as the key on the Cadastre unless 3ID is implemented to stay consistent with governance but with affordances to force/allow the user to still toggle between wallets to interact with the respective land parcels.

**Comment by codynhat** [comment]
After synchronous discussion, we are leaving the behavior as is for now. Users will only be able to edit docs if they have the specific wallet selected in Metamask.

Also, I believe the linking of accounts is a 3ID specific thing

https://developers.idx.xyz/guides/definitions/default/#3id-keychain

However, it seems to be just an IDX definition, which means any DID could implement it if they wanted to?
