### ISSUE TITLE
Different versions of bootstrap

### ISSUE THREAD

**Issue by lolboysg** [Geo-Web-Project/cadastre#221]
**Describe the bug**
In this repository, there is two not compatible versions of bootstrap and react-bootstrap. This leads to some problems such as style not found on components like the close icon on dismissible alert

**To Reproduce**
1. Add a dismissible to any alert
2. See the style of the close icon not being right r

**Expected behavior**
Both versions of bootstrap and bootstrap-react should be compatible

**Screenshots**
<img width="270" alt="Screenshot 2022-08-05 at 22 44 59" src="https://user-images.githubusercontent.com/72015889/183160022-1e4bea40-2ce5-4932-bb6d-4f9a35e0058a.png">

**Desktop:**
 - OS: MACOSX
 - Browser firefox
 - Version 103.0.1

**Comment by gravenp** [comment]
PR already merged. Issue closed.
