### ISSUE TITLE
Parcels not fully displayed

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#223]
**Describe the bug**
Currently, the Cadastre only allows rectangular parcel claims, but after some parcels are successfully claimed, they will consistently render on the map as "incomplete."

**To Reproduce**
1. Sign in to the Cadastre
2. Search for Oyster Bay, New York, United States & zoom in on the parcels near the beach just north of the map marker
3. Two of these parcels appear to be missing several coordinates from the end of the top-right of their rectangle shape

Either the full parcel isn't being fully rendered for some reason (issue with front-end or the Graph?) or when the claim transaction was processed, the full coordinate path wasn't recorded (contract issue).

**Expected behavior**
All parcels should be complete rectangles.

**Additional Context**
If this turns out to not be a front-end issue, we can close this issue and recreate it in the appropriate repo.

**Comment by tnrdd** [comment]
Could this be because these parcels were claimed before #32 was fixed, so it only shows the max amount of coordinates that could have been claimed? These parcels are smaller than the current max parcel size enforced in the frontend, but maybe the max in the contract was lower?
