### ISSUE TITLE
Refactor code to have a global style

### ISSUE THREAD

**Issue by 0xtekgrinder** [Geo-Web-Project/cadastre#226]
**Is your feature request related to a problem? Please describe.**
The code miss some coherence between files, for example there is still a javascript file which is ClaimInfo.js or sometimes there is button react component being used and not Bootstrap one

**Describe the solution you'd like**
Refactor a part of the code to convert all javascript files to .tsx and change all react components that can be changed to bootstrap components

**Comment by gravenp** [comment]
Closed with https://github.com/Geo-Web-Project/cadastre/pull/233.
