### ISSUE TITLE
Infura call is reaching a rate limit

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#227]
**Describe the bug**
The console is showing a bunch of 429s being received from Infura. The Infura endpoint being called is not using the Geo Web project ID. There may be some built-in Infura provider somewhere that is being used instead.

We should find this provider and replace it with a configurable one.

**Comment by gravenp** [comment]
Fixed with https://github.com/Geo-Web-Project/cadastre/pull/228
