### ISSUE TITLE
Ceramic content updates are failing

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#248]
**Describe the bug**
`Name` and `Content Link` updates are failing to process during claims and edits. This is happening on both the staging env and prod.

Dev Console Errors:

POST https://g12-a-ceramic.3boxlabs.com/api/v0/streams 500

95-31d57f0cb938be90.js:1 Uncaught (in promise) Error: HTTP request to 'https://g12-a-ceramic.3boxlabs.com/api/v0/streams' failed with status '': {"error":"Can not verify signature for commit bagcqceramrtsnh6i4dcht72x6xmqvod267p5h5vwagwanpzqkqp57jy5fg2a: Signature does not belong to issuer"}
    at Ae (95-31d57f0cb938be90.js:1:1684229)
    at async Ie.createFromGenesis (95-31d57f0cb938be90.js:1:1685504)
    at async ht.createStreamFromGenesis (95-31d57f0cb938be90.js:1:1696713)

**Comment by codynhat** [comment]
We are going to be switching to our own mainnet node soon. Let's see if that fixes it before trying anything else.

**Comment by gravenp** [comment]
> We are going to be switching to our own mainnet node soon. Let's see if that fixes it before trying anything else.

That's good by me. I'll stand-by for testing.

**Comment by gravenp** [comment]
This has been fixed by subsequent changes.
