### ISSUE TITLE
Direct Ceramic links to Tiles app

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#26]
Ceramic links on a parcel will currently link to a gateway in a new tab.

We should replace these links to go to the [Tiles](https://tiles.mechanaut.xyz/) app instead. Created by @oaksprout and @isidorosp

**Comment by oaksprout** [comment]
Let me know if I can help make this happen!

**Comment by codynhat** [comment]
@oaksprout Would you be interested in completing this work for a small bounty? 

We are experimenting with using funds from our [Gitcoin Grant](https://gitcoin.co/grants/1403/geo-web) for bounties as well as [SourceCred](https://sourcecred.io) distributions.

**Comment by oaksprout** [comment]
Yeah for sure! Don't worry about the Gitcoin grant (I'm actually just about to fund you guys so seems a bit cyclical haha). Super excited about what you guys are working on so just happy to create an integration!

**Comment by codynhat** [comment]
Great, thanks! Even without a bounty, all contributions will earn some [Cred](https://sourcecred.io/). Let me know if you want to discuss this further.

**Comment by gravenp** [comment]
Closed with https://github.com/Geo-Web-Project/cadastre/pull/58
