### ISSUE TITLE
Update the minimum `For Sale Price` entry validation for claims

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#284]
In https://github.com/Geo-Web-Project/cadastre/pull/276, we implemented Cadastre requirements to support the minimum `For Sale` Price`.

Either I missed something in testing or a subsequent change resulted in the `For Sale Price` entry validation for Claims not being updated. It should match the validation and text that is being used for Reclaims and Edits:

“For Sale Price must be greater than or equal to 0.005” with corresponding logic.

**Comment by gravenp** [comment]
Now I'm seeing the right validation again.. Not sure what was up, but closing this issue.

**Comment by codynhat** [comment]
May have been a merge issue
