### ISSUE TITLE
Update the Cadastre header

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#304]
![Header_v2](https://user-images.githubusercontent.com/15019279/201734720-5e703222-90f6-44ef-aeca-314012fc40fd.png)

**Requirements**
- Move the Geo Web logo and page title ("Cadastre") to the left of the page
  - Add a "BETA" tag to the title in a "superscript-like" location
  - Remove the subtitle
  - Center the logo and Cadastre vertically in the header
- Create a new middle header element:
  - "XX.XXXX ETHx" (Live updating value on cumulative `Network Fee` funds paid into the Beneficiary--includes streamed and lump sum payments)
  - "Public Goods Funding Raised"
  - Add a tooltip that shows when the user hovers over the element
     - "100% of the Network Fees collected from the Geo Web's land market are used to fund public goods. This is the total collected so far."
- Add a new menu element to the right of the wallet element
  - Assets
    - https://fonts.google.com/icons?icon.query=more+horiz
    - https://fonts.google.com/icons?icon.query=open+in+new
  - Opens on user clicks and closes on interaction with links or elements outside of the menu
  - Links
    - https://faucet.paradigm.xyz/
    - https://docs.geoweb.network/
    - FAQ = current FAQ lightbox
    -  https://discord.com/invite/reXgPru7ck
    - https://twitter.com/thegeoweb

**Comment by codynhat** [comment]
> Note: I'm open to ideas for better ways to implement this. With this approach when we send ETHx out to fund public goods, we'll need to add a corresponding manual adjustment to the value of this variable.

There is a way to fetch the total amount streamed for each stream. This could be a way to calculate it in the future.

For the subtitle, what do you think about making this a banner with a different color? To make it stand out more.

**Comment by gravenp** [comment]
> For the subtitle, what do you think about making this a banner with a different color? To make it stand out more.

Yeah, probably a good call to emphasize it more. I'll play around with some designs.

**Comment by gravenp** [comment]
@tnrdd & @codynhat, I've updated the ticket requirements and mockup above.
