### ISSUE TITLE
Enforce a max parcel claim size (testnet)

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#32]
**User Stories**
As a user, I want all of my submitted land claims to be successfully processed on the blockchain and displayed on the Cadastre. As a project steward, I want to prevent excessively sprawling land claims, especially in the early market.

**Why Is this Needed**
There is no limit to the land parcel claim size enforced from the front end, but there is a practical limit to what can be fit in the transaction/block and/or what is returned by the Graph.  Excessively large parcels also introduce transactional friction to the land market.

Note: Large land claims are currently accepted and the transaction is processed, but occasionally the result is an "incomplete" claim shown on the front end (example below). There appears to be a mismatch between the chain and the Cadastre because users are unable to claim the coordinates "dropped" in the original transaction.

<img width="591" alt="Screen Shot 2021-04-05 at 10 26 46 AM" src="https://user-images.githubusercontent.com/15019279/113598809-f0d84500-95fa-11eb-8237-69f00eb7c962.png">

**Details**
Update the ClaimInfo card (https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimInfo.js) according to the requirements and wireframe below (including replacing existing text).
1. Create a variable to enforce a maximum parcel claim size (# of coordinates). 
- Optimisitic Kovan can be set to 900 to start.
2. Dynamically calculate and display the number of coordinates currently selected by the user.
3. If the user selection exceeds the maximum claim size, change the claim selection to the invalid state (red color) and disallow the second click to lock in the parcel.
4. The Cancel button should clear the claim selection and exit claim mode.

![Max Claim](https://user-images.githubusercontent.com/15019279/177854036-8fbc7e67-6bae-4875-b699-5179c7c55729.png)

**Comment by gravenp** [comment]
We will still want to enforce a max claim size on the zkSync 2.0 testnet that is appropriate for the grid size and gas usage. Keeping this in the backlog.

**Comment by ziatsnick** [comment]
@gravenp One additional comment for consideration on this. Is it possible to build in functionality for a user to drag the yellow squares to the edge of the screen and the map will move accordingly? Currently, if you drag the yellow squares to the edge of the screen, the map stays still. If this is an easy addition, I think it would be a useful feature in case the address that the user enters does not fully capture all the land that the user wants to purchase.

**Comment by gravenp** [comment]
Thanks for the suggestion @ziatsnick. We can definitely look into it. Right now during claim mode, we just maintain MapBox's default navigation UX, so you are able to click and drag to move the map window and expand your parcel. I'll at least add a reference to that in the info panel if we aren't able to implement an alternative.

**Comment by ziatsnick** [comment]
@gravenp That makes sense. Clicking and dragging works well too, so no big deal if it’s too much of a hassle to add.

While we are on the topic, I do have one more VERY slight recommendation. When a user is in claim mode and then zooms out, there is a point at which the yellow squares freeze (I assume this occurs on purpose because the zoom is too far out). In that case, I think it would be useful to add a note that pops up on the screen that informs the user that the zoom is too far to claim land.
