### ISSUE TITLE
Error on saving media gallery

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#34]
Currently getting an error, "Unknown DID" when saving changes to the media gallery. Will add more details.

**Comment by codynhat** [comment]
This is probably caused by a breaking change to how 3IDs are derived using the CAIP-Link doctype.

This can be fixed with a migration. If any changes are attempted and this error is found, the Cadastre will need to generate a new set of documents using the new 3ID as the controller and resubmit the root CID to the registry.

The only change in user experience is a one-time blockchain transaction that is required to perform the migration.

**Comment by codynhat** [comment]
One side note: 

This could be mitigated if the NFT DID method was used as the controller of the root document. If that were the case, no transaction would be needed. A more simple migration could be done for any documents owned by the 3ID that are linked from the root document.

**Comment by codynhat** [comment]
@gravenp What are your thoughts on this? Is it alright to require a transaction for changes to existing parcel content?

**Comment by gravenp** [comment]
If it's a one-time transaction, that's fine. We definitely don't want to require a blockchain transaction for each content update going forward (even just testnet). 

My question is just about timing and workload. NFT DID isn't going to be ready for a while and other breaking changes may pop up as Ceramic moves to their mainnet. We just want to do this once, so depending on your comfort level with the current state of Ceramic, we should slot this accordingly.
