### ISSUE TITLE
Show parcel information on mouse hover

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#451]
**Description**
Show basic parcel information from the Geo Web subgraph in a tooltip-like bubble when the user hovers their mouse over a parcel:
- Parcel Name (fallback to ID)
- Link (omit if none)
- For Sale Price

![Roll-Over View](https://github.com/Geo-Web-Project/cadastre/assets/15019279/3585547d-7107-4783-9c0b-bdb0ed34b7e8)

**Comment by RenanCQueiroz** [comment]
Hello. I saw the bounty on Dework. Do you think 400 usd is a good price for this ?

**Comment by gravenp** [comment]
Going to close this issue for now. Will reopen a fresh ticket after we complete our move to MUD content linking. Parcel name & link may move to the NFT itself.
