### ISSUE TITLE
Add a Profile UI element which can be used to claim land transfer proceeds

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#52]
**Background**
For security reasons, proceeds from forced land transfers are not deposited directly into the previous land holder's wallet (https://docs.soliditylang.org/en/v0.8.6/common-patterns.html#withdrawal-pattern). We need to add a way for users to claim/withdraw such funds.

**Description**
Add a profile modal triggered by clicking on the connected wallet address in the header. The modal will be used for claiming land transfer funds. In the future, this may be used for additional "account" features like DID profile, transaction history, parcel portfolio, etc.

**Requirements**
-Launch a Profile modal when the user clicks on their wallet address in the header
-Display values for full wallet address, full wallet balance, & unclaimed transfer proceeds in the modal
-Add a "Disconnect" button which allows the user to disconnect the current wallet
-Display an animated notification icon in the wallet header element when there are funds available to be claimed (shown in place of the default profile icon when active) 
-Display a button to "Claim Proceeds" in the modal when there are funds from a land transfer available to withdraw
-Trigger the appropriate smart contract/wallet interaction when the user clicks the Claim Proceeds button

**Related Issues**
https://github.com/Geo-Web-Project/cadastre/issues/57
https://github.com/Geo-Web-Project/cadastre/issues/28

**Comment by gravenp** [comment]
<img width="718" alt="Profile Modal" src="https://user-images.githubusercontent.com/15019279/129494276-79f1da47-3114-4cd2-8157-88c4e6c200cf.png">
 
Mockup from Figma attached.

**Comment by gravenp** [comment]
@codynhat is `_transferSellerFeeReimbursement` the relevant function for the claim functionality on this ticket from https://github.com/Geo-Web-Project/core-contracts/blob/main/contracts/GeoWebAdmin_v0.sol? What about displaying and notifying on the existence of the unclaimed fee?

**Comment by codynhat** [comment]
A land owner can claim their land transfer proceeds by calling `withdraw` https://github.com/Geo-Web-Project/core-contracts/blob/main/contracts/GeoWebAdminNative_v0.sol#L73

This can be called from Ethers.js and the Cadastre by `adminContract.withdraw()` [here](https://github.com/Geo-Web-Project/cadastre/blob/main/pages/index.js#L83)

**Comment by gravenp** [comment]
This issue won't be relevant anymore after the move to streaming payments. ETHx is used for streaming and an ERC20 token that doesn't need to follow this ETH security pattern.
