### ISSUE TITLE
Add search functionality to the Cadastre

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#62]
**Background**
The map on the Cadastre is cumbersome and slow to navigate. Finding a specific location for a parcel claim requires recognition of landmarks and manual zoom.

**Description**
Add search functionality to the Cadastre map UI

**Requirements**
- Add a search bar (type, enter, clear)
- Search by address
- Search by real world place names

**Comment by gravenp** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

**Comment by gravenp** [comment]
@10dimensions https://github.com/Geo-Web-Project/cadastre/pull/73 is only merged into staging at this point, so this ticket was still open. I'm noticing now that I'm not able to claim a multi-coordinate parcel.

When starting a claim, the grid should pop up and the user should be able to expand the claim from one coordinate to multiple and that's not happening now. I'm thinking it's likely related to the Search Bar addition. 

Could you take a look then we'll close and open new tickets as appropriate?

**Comment by 10dimensions** [comment]
Yes @gravenp . Just now noticing this.
Only the first grid selection works, and the overall mouse event is prevented.

Debugging this today.
