### ISSUE TITLE
Media Gallery pins showing as failed (but succeed in the background)

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#68]
Browser: Firefox (CORS disabled)
Env: Staging

When pinning content on the media gallery, all pins are showing as failed. Sample log attached, but issue follows this pattern:

1) Object ______ is not in queue. Pinning again... 
2) Link is already in pinset: ____ (Note: This is logged even if the object pinned is brand new and has never been pinned before)
3) XHRPOSThttps://storage-workers.geo-web.workers.dev/pinset/did:3:_____/request [[HTTP/3 500 Internal Server Error 10278ms]]

Pin spinner continues until user closes the modal. Upon return, the pins show as failed.

After waiting 5-10 min, the object does appear to get pinned successfully in the background, but still shows as "Pin Failed" or "In Process" in the modal upon refresh:

- The "storage used" number at the bottom of the modal is incremented up 
- The object appears in the IPFS pinset found by clicking on the "storage used" link.

[Failed Pinning Logs.txt](https://github.com/Geo-Web-Project/storage-workers/files/7051690/Failed.Pinning.Logs.txt)

**Comment by codynhat** [comment]
There is an old DID that is stuck on `Provisioning Storage For Media Gallery...`

It seems that the **current** pinset CID for this DID is not being found (and was probably never pinned). Investigating further how we can handle this case.

**Comment by codynhat** [comment]
Adding an error message and button to allow user to reset pinset. This will set their IDX record to an empty pinset.
