### ISSUE TITLE
Show progress on media gallery item upload

### ISSUE THREAD

**Issue by codynhat** [Geo-Web-Project/cadastre#88]
Should we show upload progress in the UI when uploading a large file to the media gallery?

**Comment by gravenp** [comment]
That would definitely be a big UX improvement... 

Is that a rhetorical question? Is that progress data readily measurable/available?

**Comment by codynhat** [comment]
I'm not sure. This would include the adding of the item to IPFS as well as the preload node waiting to receive. I think the former has built-in progress tracking.

**Comment by gravenp** [comment]
No longer needed after https://github.com/Geo-Web-Project/cadastre/pull/183
