### ISSUE TITLE
Cadastre Redesign - Simple Claim View

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#95]
View For: Any user that starts a claim (single-click on an unpopulated coordinate on the map) after the fair launch period
Current Reference: https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimInfo.js & https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimAction.js

1. Display the existing claim instructions, wireframe 1.1 in the left panel upon the first click ([mimics existing functionality](https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/ClaimInfo.js))
2. Upon a second click, display the left panel as shown in wireframe 1.2
3. Move all field labels above the entry box (instead of light text in the field as is the current design) 
4. The left panel should be scrollable independent of the map
5. `Parcel Name` and `URI` should be written to the appropriate Ceramic streams fields (mimic existing functionality)
6. The `For Sale Price` is used to calculate the `x% Network Fee` field based on the current network fee rate pulled form the Geo Web core contracts
    * `For Sale Price` is a stored variable for each parcel
7. The % displayed in the Network Fee label should be a variable pulled from the applicable network fee rate
9. The `Claim Payout` field will always = 0.00 (shown for informational reinforcement)
10. The `Stream` field is equal to the Network Fee rate divided by 31,536,000 (seconds in a 365 day year). This value is added to the user's new/existing SuperFluid payment stream
11. The `Stream Buffer` field is equal to the deposit required to open/update the stream in the SuperFluid protocol
12. The `Wrap to ETHx` opens the Wrap ETH modal shown in wireframe 11.1
13. The `Claim` button submits the entered data to the appropriate Ceramic stream fields+pinning and smart contract transactions (which require wallet signing)
14. Display the "Streaming Info Box" defined in https://github.com/Geo-Web-Project/cadastre/issues/94 below the transaction submission buttons.
15. Conform styling to existing Cadastre styling (wireframes below show functionality and spacing).
<img width="748" alt="1 1" src="https://user-images.githubusercontent.com/15019279/160210525-869042b3-0e89-4323-aa9e-5c14b052651d.png">

<img width="843" alt="1 2" src="https://user-images.githubusercontent.com/15019279/160210541-73093df4-83b8-4a7b-b05c-7286343324b8.png">

**Bounty Overview**
Size = M
Payment = 500 DAI (for the two issues)
To Be Completed With: https://github.com/Geo-Web-Project/cadastre/issues/101
Assignee = 

**Bounty Submission**
When work is complete, please create PR with your work and request review from both @codynhat & @gravenp. @gravenp will handle logistics of payment with you privately.

**Comment by zhyd1997** [comment]
Hi @gravenp 

How to understand the item 10 above:

>the deposit required to open/update the stream in the SuperFluid protocol

**Comment by zhyd1997** [comment]
is this formula correct?

> Security Deposit = 4 * ( Monthly Stream Rate / (30 * 24) )

If so, what's the stream rate in our codebase?

**Comment by gravenp** [comment]
@zhyd1997 our flows are sent to our Super App, so the deposits required are actually x2 the standard deposit. See the table here: https://docs.superfluid.finance/superfluid/protocol-developers/super-apps/super-app#super-app-deposits

On testnets, the required deposit will be two hours (2 * 60 * 60) multiplied by the `flowRate` (stored as a per-second value rather than monthly). 

On this screen, we want to display the **change** in the required deposit based on the user's entry: (New `flowRate` - Old `flowRate) * 7200.

@codynhat did I get that all right?

**Comment by codynhat** [comment]
Yes, that sounds right. This is the minimum deposit though, and the user really needs to wrap more ETHx if they do not have any incoming streams already.

**Comment by gravenp** [comment]
> the user really needs to wrap more ETHx if they do not have any incoming streams already.

Yes, after this transaction to initiate/update the stream is complete, the wallet should still always maintain a non-zero ETHx balance (which does not include the security deposit) to avoid having the stream closed.

**Comment by zhyd1997** [comment]
@codynhat @gravenp 

So here `StreamBuffer` = (`flowRate` - `oldFlowRate` if no exsiting streams, it should be *0*) * 60 * 60 * 2?

`flowRate` is equal to the `Stream` field above.

**Comment by gravenp** [comment]
Both the Stream and Stream Buffer fields on this page should display the respective changes in those values as a result of the transaction (we want to show the impact of what they're signing for).

So, you have the correct formula for the value to be displayed for Stream Buffer.  

Stream should equal `flowRate` - `oldFlowRate`.

**Comment by zhyd1997** [comment]
@gravenp 

> Stream should equal `flowRate` - `oldFlowRate`.

If so, the `Stream` value may be different from item 9 above?

> The Stream field is equal to the Network Fee rate divided by 31,536,000 (seconds in a 365 day year).

**Comment by codynhat** [comment]
You have this correct in the current PR. `networkFeeRatePerSecond` is the same as `flowRate` - `oldFlowRate`

**Comment by codynhat** [comment]
@gravenp Does this issue include the actual claim functionality or just the view? Same question for the other bounties?

**Comment by gravenp** [comment]
@codynhat Yes, these bounties should include the interaction with the smart contracts (claims in this case). Req number 12 on this ticket represents that interaction.

**Comment by gravenp** [comment]
Closing this ticket. Bounty paid with #101.
