### ISSUE TITLE
Cadastre Redesign - Auction Bid View

### ISSUE THREAD

**Issue by gravenp** [Geo-Web-Project/cadastre#97]
View For: A user that clicks on a valid parcel that is owned by a different wallet and DOES NOT have an outstanding bid
Current Reference: https://github.com/Geo-Web-Project/cadastre/blob/main/components/cards/PurchaseAction.js

1. When a user other than the licensor clicks on a valid parcel without any oustanding bids, display the panel as defined in wireframe 3.1.
2. The "How do Geo Web auctions work?" link should open a modal/lightbox with the text shown in the wireframe.
3. The `For Sale Price` for an Auction bid must be greater than or equal to the current `For Sale Price`
    * Show an error message and don't calculate the Network Fee field or Transaction Summary Section if the `For Sale Price` bid is less than the current one.
4. Transaction Summary
    * Collateral Deposit = New `For Sale Price`
    * Purchase Payment = Previous `For Sale Price`
    * Refundable Collateral =  New `For Sale Price` - Previous `For Sale Price`
    * Stream & Stream Buffer are calculated and displayed as in other views
5. The `Wrap to ETHx` opens the Wrap ETH modal shown in wireframe 11.1
6. The `Submit` button submits the entered data to the appropriate Ceramic stream fields+pinning and smart contract transactions (which require wallet signing)
7. Display the "Streaming Info Box" defined in https://github.com/Geo-Web-Project/cadastre/issues/94 below the transaction submission buttons.
8. Conform styling to existing Cadastre styling (wireframes below show functionality and spacing).
<img width="753" alt="3 1" src="https://user-images.githubusercontent.com/15019279/160210778-e46bd50e-1059-4ee3-b452-36e7d569e263.png">

<img width="753" alt="3 2" src="https://user-images.githubusercontent.com/15019279/160210785-b362d24b-7133-462b-bcdc-7693a1ef3997.png">

<img width="876" alt="3 3" src="https://user-images.githubusercontent.com/15019279/160210793-6a06c4d6-1c4e-4efc-a037-1f98da965e53.png">

Bounty Overview
Size = M
Payment = 500 DAI (for the three issues)
To Be Completed With: https://github.com/Geo-Web-Project/cadastre/issues/98 & https://github.com/Geo-Web-Project/cadastre/issues/100
Assignee =

Bounty Submission
When work is complete, please create PR with your work and request review from both @codynhat & @gravenp. @gravenp will handle the logistics of payment with you privately.

**Comment by gravenp** [comment]
@zhyd1997 Note: Cody created the pop-up window shown in the first wireframe (AuctionInstructions.tsx)  as a part of https://github.com/Geo-Web-Project/cadastre/pull/140

**Comment by codynhat** [comment]
@gravenp There is a case that is missing in these tickets.

When the current owner wants to accept a bid, one of two things can happen.
1. If the owner has multiple parcels, they decrease their flow by the value of the parcel they are accept a bid for, and the transfer triggers (currently the spec here)
2. (Missing case) If the owner only has one parcel, they _delete_ their flow, but the transfer cannot be triggered. It will need to be triggered similar to #100 when the bid period elapses

For this missing case, should the UI be just like #100?

**Comment by gravenp** [comment]
> 2\. (Missing case) If the owner only has one parcel, they _delete_ their flow, but the transfer cannot be triggered. It will need to be triggered similar to [Cadastre Redesign - Auction Transfer #100](https://github.com/Geo-Web-Project/cadastre/issues/100) when the bid period elapses

Are you talking about a situation where the previous owner deletes their flow outside of the normal Cadastre functions (eg on the SuperFluid dashboard or with direct contract interaction) and this does not trigger the license transfer? Are there any reasons when interacting through the Cadastre that could create the situation where a "transfer cannot be triggered?" 

If I'm understanding the scenario correctly, yeah I think any outstanding parcels that have open bids should end up on a screen with functionality represented in https://github.com/Geo-Web-Project/cadastre/issues/100. Could the auction deadline be effectively moved up to the time of flow deletion? 

If the user that's deleting their flow has parcels that don't have outstanding bids, they should go to the normal foreclosure process.

**Comment by codynhat** [comment]
That situation can also happen. But what I'm talking about in 2) is when a user "properly" accepts a bid, but it is for the only parcel they own. In this case, they are lowering their flow to 0, which is a delete.

In either case, yes this effectively moves up the auction deadline to the time of deletion. So we can show #100

**Comment by gravenp** [comment]
So when a flow is deleted instead of lowered, we're prevented from also automatically doing the second step of transferring the license?

Regardless, yes it sounds like showing https://github.com/Geo-Web-Project/cadastre/issues/100 is the right way to go. As long as the parcel stays in focus after accepting the bid, the former licensor would immediately see the trigger function button without having to renavigate to the parcel, correct?

**Comment by codynhat** [comment]
Those are both correct.
